/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import BE.ButtonClickCounter;
import BE.Firemen;
import BLL.TimeLogBLL;
import java.sql.SQLException;
import java.sql.Time;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;

/**
 *
 * @author Zainz
 */
public class MainFrame extends javax.swing.JFrame {
    
    ArrayList<Firemen>  firemen;
    
    TimeLogBLL          tlb;
    
    Firemen             fir1,fir2,fir3,fir4,fir5,fir6,fir7,fir8,fir9,fir10,fir11,
                        fir12,fir13,fir14,fir15,fir16,fir17,fir18,fir19,fir20,
                        fir21,fir22,fir23,fir24,fir25,fir26,fir27,fir28,fir29,
                        fir30,fir31,fir32,fir33,fir34,fir35,fir36;
                                
    ButtonClickCounter  tbc1,tbc2,tbc3,tbc4,tbc5,tbc6,tbc7,tbc8,tbc9,tbc10,tbc11,
                        tbc12,tbc13,tbc14,tbc15,tbc16,tbc17,tbc18,tbc19,tbc20,
                        tbc21,tbc22,tbc23,tbc24,tbc25,tbc26,tbc27,tbc28,tbc29,
                        tbc30,tbc31,tbc32,tbc33,tbc34,tbc35,tbc36;
    
    String              lit1, lit2, lit3, lit4, lit5, lit6, lit7, lit8, lit9, lit10,
                        lit11, lit12, lit13, lit14, lit15, lit16, lit17, lit18, lit19,
                        lit20, lit21, lit22, lit23, lit24, lit25, lit26, lit27, lit28,
                        lit29, lit30, lit31, lit32, lit33, lit34, lit35, lit36;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        tlb = new TimeLogBLL();
        
        try{
            firemen = tlb.getFiremen();
        } catch(SQLException e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
        
        fir1 = firemen.get(0);
        fir2 = firemen.get(1);
        fir3 = firemen.get(2);
        fir4 = firemen.get(3);
        fir5 = firemen.get(4);
        fir6 = firemen.get(5);
        fir7 = firemen.get(1);
        fir8 = firemen.get(1);
        fir9 = firemen.get(1);
        fir10 = firemen.get(1);
        fir11 = firemen.get(1);
        fir12 = firemen.get(1);
        fir13 = firemen.get(1);
        fir14 = firemen.get(1);
        fir15 = firemen.get(1);
        fir16 = firemen.get(1);
        fir17 = firemen.get(1);
        fir18 = firemen.get(1);
        fir19 = firemen.get(1);
        fir20 = firemen.get(1);
        fir21 = firemen.get(1);
        fir22 = firemen.get(1);
        fir23 = firemen.get(1);
        fir24 = firemen.get(1);
        fir25 = firemen.get(1);
        fir26 = firemen.get(1);
        fir27 = firemen.get(1);
        fir28 = firemen.get(1);
        fir29 = firemen.get(1);
        fir30 = firemen.get(1);
        fir31 = firemen.get(1);
        fir32 = firemen.get(1);
        fir33 = firemen.get(1);
        fir34 = firemen.get(1);
        fir35 = firemen.get(1);
        fir36 = firemen.get(1);
        
        tbc1 = new ButtonClickCounter(0);
        tbc2 = new ButtonClickCounter(0);
        tbc3 = new ButtonClickCounter(0);
        tbc4 = new ButtonClickCounter(0);
        tbc5 = new ButtonClickCounter(0);
        tbc6 = new ButtonClickCounter(0);
        tbc7 = new ButtonClickCounter(0);
        tbc8 = new ButtonClickCounter(0);
        tbc9 = new ButtonClickCounter(0);
        tbc10 = new ButtonClickCounter(0);
        tbc11 = new ButtonClickCounter(0);
        tbc12 = new ButtonClickCounter(0);
        tbc13 = new ButtonClickCounter(0);
        tbc14 = new ButtonClickCounter(0);
        tbc15 = new ButtonClickCounter(0);
        tbc16 = new ButtonClickCounter(0);
        tbc17 = new ButtonClickCounter(0);
        tbc18 = new ButtonClickCounter(0);
        tbc19 = new ButtonClickCounter(0);
        tbc20 = new ButtonClickCounter(0);
        tbc21 = new ButtonClickCounter(0);
        tbc22 = new ButtonClickCounter(0);
        tbc23 = new ButtonClickCounter(0);
        tbc24 = new ButtonClickCounter(0);
        tbc25 = new ButtonClickCounter(0);
        tbc26 = new ButtonClickCounter(0);
        tbc27 = new ButtonClickCounter(0);
        tbc28 = new ButtonClickCounter(0);
        tbc29 = new ButtonClickCounter(0);
        tbc30 = new ButtonClickCounter(0);
        tbc31 = new ButtonClickCounter(0);
        tbc32 = new ButtonClickCounter(0);
        tbc33 = new ButtonClickCounter(0);
        tbc34 = new ButtonClickCounter(0);
        tbc35 = new ButtonClickCounter(0);
        tbc36 = new ButtonClickCounter(0);
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new ColoredToggleButton(fir1);
        jToggleButton2 = new ColoredToggleButton(fir12);
        jToggleButton3 = new ColoredToggleButton(fir23);
        jToggleButton4 = new ColoredToggleButton(fir30);
        jToggleButton5 = new ColoredToggleButton(fir31);
        jToggleButton6 = new ColoredToggleButton(fir32);
        jToggleButton7 = new ColoredToggleButton(fir33);
        jToggleButton8 = new ColoredToggleButton(fir34);
        jToggleButton9 = new ColoredToggleButton(fir35);
        jToggleButton10 = new ColoredToggleButton(fir2);
        jToggleButton11 = new ColoredToggleButton(fir3);
        jToggleButton12 = new ColoredToggleButton(fir4);
        jToggleButton13 = new ColoredToggleButton(fir5);
        jToggleButton14 = new ColoredToggleButton(fir6);
        jToggleButton15 = new ColoredToggleButton(fir7);
        jToggleButton16 = new ColoredToggleButton(fir8);
        jToggleButton17 = new ColoredToggleButton(fir9);
        jToggleButton18 = new ColoredToggleButton(fir10);
        jToggleButton19 = new ColoredToggleButton(fir11);
        jToggleButton20 = new ColoredToggleButton(fir13);
        jToggleButton21 = new ColoredToggleButton(fir14);
        jToggleButton22 = new ColoredToggleButton(fir15);
        jToggleButton23 = new ColoredToggleButton(fir16);
        jToggleButton24 = new ColoredToggleButton(fir17);
        jToggleButton25 = new ColoredToggleButton(fir18);
        jToggleButton26 = new ColoredToggleButton(fir19);
        jToggleButton27 = new ColoredToggleButton(fir20);
        jToggleButton28 = new ColoredToggleButton(fir21);
        jToggleButton29 = new ColoredToggleButton(fir22);
        jToggleButton30 = new ColoredToggleButton(fir24);
        jToggleButton31 = new ColoredToggleButton(fir25);
        jToggleButton32 = new ColoredToggleButton(fir26);
        jToggleButton33 = new ColoredToggleButton(fir27);
        jToggleButton34 = new ColoredToggleButton(fir28);
        jToggleButton35 = new ColoredToggleButton(fir29);
        jToggleButton36 = new ColoredToggleButton(fir36);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 780));
        setResizable(false);

        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });

        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });

        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });

        jToggleButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton6ActionPerformed(evt);
            }
        });

        jToggleButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton7ActionPerformed(evt);
            }
        });

        jToggleButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton8ActionPerformed(evt);
            }
        });

        jToggleButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton9ActionPerformed(evt);
            }
        });

        jToggleButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton10ActionPerformed(evt);
            }
        });

        jToggleButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton11ActionPerformed(evt);
            }
        });

        jToggleButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton12ActionPerformed(evt);
            }
        });

        jToggleButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton13ActionPerformed(evt);
            }
        });

        jToggleButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton14ActionPerformed(evt);
            }
        });

        jToggleButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton15ActionPerformed(evt);
            }
        });

        jToggleButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton16ActionPerformed(evt);
            }
        });

        jToggleButton17.setToolTipText("");
        jToggleButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton17ActionPerformed(evt);
            }
        });

        jToggleButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton18ActionPerformed(evt);
            }
        });

        jToggleButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton19ActionPerformed(evt);
            }
        });

        jToggleButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton20ActionPerformed(evt);
            }
        });

        jToggleButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton21ActionPerformed(evt);
            }
        });

        jToggleButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton22ActionPerformed(evt);
            }
        });

        jToggleButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton23ActionPerformed(evt);
            }
        });

        jToggleButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton24ActionPerformed(evt);
            }
        });

        jToggleButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton25ActionPerformed(evt);
            }
        });

        jToggleButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton26ActionPerformed(evt);
            }
        });

        jToggleButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton27ActionPerformed(evt);
            }
        });

        jToggleButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton28ActionPerformed(evt);
            }
        });

        jToggleButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton29ActionPerformed(evt);
            }
        });

        jToggleButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton30ActionPerformed(evt);
            }
        });

        jToggleButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton31ActionPerformed(evt);
            }
        });

        jToggleButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton32ActionPerformed(evt);
            }
        });

        jToggleButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton33ActionPerformed(evt);
            }
        });

        jToggleButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton34ActionPerformed(evt);
            }
        });

        jToggleButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton35ActionPerformed(evt);
            }
        });

        jToggleButton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton36ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToggleButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton32, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton33, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton34, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton35, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton36, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToggleButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton27, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton28, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton29, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton30, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton31, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton25, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton26, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToggleButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jToggleButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jToggleButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jToggleButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jToggleButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jToggleButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jToggleButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jToggleButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jToggleButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton25, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton26, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton27, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton28, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton29, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton30, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton31, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton32, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton33, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton34, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton35, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton36, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        tbc1.up();
        
        if(tbc1.value() == 2) new LogOutWindow(this, tbc1, jToggleButton1, fir1, lit1).setVisible(true);
        
        if(tbc1.value() % 2 == 0) jToggleButton1.setSelected(false);
        if(tbc1.value() % 2 == 1) jToggleButton1.setSelected(true);
        
        if(tbc1.value() == 1) lit1 = new SimpleDateFormat("HH:mm:ss").format(new Timestamp(System.currentTimeMillis()));
        
        if(tbc1.value() >= 2) tbc1.down();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        tbc2.up();
        
        if(tbc2.value()==2) new LogOutWindow(this, tbc2, jToggleButton2, fir12).setVisible(true);
        if(tbc2.value()>=2) tbc2.down();
            
        if(tbc2.value() % 2 == 0) jToggleButton2.setSelected(false);
        if(tbc2.value() % 2 == 1) jToggleButton2.setSelected(true);
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton6ActionPerformed
        tbc3.up();
        
        if(tbc3.value()==2) new LogOutWindow(this, tbc3, jToggleButton6, fir32).setVisible(true);
        if(tbc3.value()>=2) tbc3.down();
            
        if(tbc3.value() % 2 == 0) jToggleButton6.setSelected(false);
        if(tbc3.value() % 2 == 1) jToggleButton6.setSelected(true);
    }//GEN-LAST:event_jToggleButton6ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        tbc4.up();
        
        if(tbc4.value()==2) new LogOutWindow(this, tbc4, jToggleButton3, fir23).setVisible(true);
        if(tbc4.value()>=2) tbc4.down();
            
        if(tbc4.value() % 2 == 0) jToggleButton3.setSelected(false);
        if(tbc4.value() % 2 == 1) jToggleButton3.setSelected(true);
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        tbc5.up();
        
        if(tbc5.value()==2) new LogOutWindow(this, tbc5, jToggleButton4, fir30).setVisible(true);
        if(tbc5.value()>=2) tbc5.down();
            
        if(tbc5.value() % 2 == 0) jToggleButton4.setSelected(false);
        if(tbc5.value() % 2 == 1) jToggleButton4.setSelected(true);
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
        tbc6.up();
        
        if(tbc6.value()==2) new LogOutWindow(this, tbc6, jToggleButton5, fir31).setVisible(true);
        if(tbc6.value()>=2) tbc6.down();
            
        if(tbc6.value() % 2 == 0) jToggleButton5.setSelected(false);
        if(tbc6.value() % 2 == 1) jToggleButton5.setSelected(true);
    }//GEN-LAST:event_jToggleButton5ActionPerformed

    private void jToggleButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton9ActionPerformed
        tbc7.up();
        
        if(tbc7.value()==2) new LogOutWindow(this, tbc7, jToggleButton9, fir35).setVisible(true);
        if(tbc7.value()>=2) tbc7.down();
            
        if(tbc7.value() % 2 == 0) jToggleButton9.setSelected(false);
        if(tbc7.value() % 2 == 1) jToggleButton9.setSelected(true);
    }//GEN-LAST:event_jToggleButton9ActionPerformed

    private void jToggleButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton10ActionPerformed
        tbc8.up();
        
        if(tbc8.value()==2) new LogOutWindow(this, tbc8, jToggleButton10, fir2).setVisible(true);
        if(tbc8.value()>=2) tbc8.down();
            
        if(tbc8.value() % 2 == 0) jToggleButton10.setSelected(false);
        if(tbc8.value() % 2 == 1) jToggleButton10.setSelected(true);
    }//GEN-LAST:event_jToggleButton10ActionPerformed

    private void jToggleButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton17ActionPerformed
        tbc9.up();
        
        if(tbc9.value()==2) new LogOutWindow(this, tbc9, jToggleButton17, fir9).setVisible(true);
        if(tbc9.value()>=2) tbc9.down();
            
        if(tbc9.value() % 2 == 0) jToggleButton17.setSelected(false);
        if(tbc9.value() % 2 == 1) jToggleButton17.setSelected(true);
    }//GEN-LAST:event_jToggleButton17ActionPerformed

    private void jToggleButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton22ActionPerformed
        tbc10.up();
        
        if(tbc10.value()==2) new LogOutWindow(this, tbc10, jToggleButton22, fir15).setVisible(true);
        if(tbc10.value()>=2) tbc10.down();
            
        if(tbc10.value() % 2 == 0) jToggleButton22.setSelected(false);
        if(tbc10.value() % 2 == 1) jToggleButton22.setSelected(true);
    }//GEN-LAST:event_jToggleButton22ActionPerformed

    private void jToggleButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton27ActionPerformed
        tbc11.up();
        
        if(tbc11.value()==2) new LogOutWindow(this, tbc11, jToggleButton27, fir20).setVisible(true);
        if(tbc11.value()>=2) tbc11.down();
            
        if(tbc11.value() % 2 == 0) jToggleButton27.setSelected(false);
        if(tbc11.value() % 2 == 1) jToggleButton27.setSelected(true);
    }//GEN-LAST:event_jToggleButton27ActionPerformed

    private void jToggleButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton32ActionPerformed
        tbc12.up();
        
        if(tbc12.value()==2) new LogOutWindow(this, tbc12, jToggleButton32, fir26).setVisible(true);
        if(tbc12.value()>=2) tbc12.down();
            
        if(tbc12.value() % 2 == 0) jToggleButton32.setSelected(false);
        if(tbc12.value() % 2 == 1) jToggleButton32.setSelected(true);
    }//GEN-LAST:event_jToggleButton32ActionPerformed

    private void jToggleButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton7ActionPerformed
        tbc13.up();
        
        if(tbc13.value()==2) new LogOutWindow(this, tbc13, jToggleButton7, fir33).setVisible(true);
        if(tbc13.value()>=2) tbc13.down();
            
        if(tbc13.value() % 2 == 0) jToggleButton7.setSelected(false);
        if(tbc13.value() % 2 == 1) jToggleButton7.setSelected(true);
    }//GEN-LAST:event_jToggleButton7ActionPerformed

    private void jToggleButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton12ActionPerformed
        tbc14.up();
        
        if(tbc14.value()==2) new LogOutWindow(this, tbc14, jToggleButton12, fir4).setVisible(true);
        if(tbc14.value()>=2) tbc14.down();
            
        if(tbc14.value() % 2 == 0) jToggleButton12.setSelected(false);
        if(tbc14.value() % 2 == 1) jToggleButton12.setSelected(true);
    }//GEN-LAST:event_jToggleButton12ActionPerformed

    private void jToggleButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton18ActionPerformed
        tbc15.up();
        
        if(tbc15.value()==2) new LogOutWindow(this, tbc15, jToggleButton18, fir10).setVisible(true);
        if(tbc15.value()>=2) tbc15.down();
            
        if(tbc15.value() % 2 == 0) jToggleButton18.setSelected(false);
        if(tbc15.value() % 2 == 1) jToggleButton18.setSelected(true);
    }//GEN-LAST:event_jToggleButton18ActionPerformed

    private void jToggleButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton23ActionPerformed
        tbc16.up();
        
        if(tbc16.value()==2) new LogOutWindow(this, tbc16, jToggleButton23, fir16).setVisible(true);
        if(tbc16.value()>=2) tbc16.down();
            
        if(tbc16.value() % 2 == 0) jToggleButton23.setSelected(false);
        if(tbc16.value() % 2 == 1) jToggleButton23.setSelected(true);
    }//GEN-LAST:event_jToggleButton23ActionPerformed

    private void jToggleButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton28ActionPerformed
        tbc17.up();
        
        if(tbc17.value()==2) new LogOutWindow(this, tbc17, jToggleButton28, fir21).setVisible(true);
        if(tbc17.value()>=2) tbc17.down();
            
        if(tbc17.value() % 2 == 0) jToggleButton28.setSelected(false);
        if(tbc17.value() % 2 == 1) jToggleButton28.setSelected(true);
    }//GEN-LAST:event_jToggleButton28ActionPerformed

    private void jToggleButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton33ActionPerformed
        tbc18.up();
        
        if(tbc18.value()==2) new LogOutWindow(this, tbc18, jToggleButton33, fir27).setVisible(true);
        if(tbc18.value()>=2) tbc18.down();
            
        if(tbc18.value() % 2 == 0) jToggleButton33.setSelected(false);
        if(tbc18.value() % 2 == 1) jToggleButton33.setSelected(true);
    }//GEN-LAST:event_jToggleButton33ActionPerformed

    private void jToggleButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton8ActionPerformed
        tbc19.up();
        
        if(tbc19.value()==2) new LogOutWindow(this, tbc19, jToggleButton8, fir34).setVisible(true);
        if(tbc19.value()>=2) tbc19.down();
            
        if(tbc19.value() % 2 == 0) jToggleButton8.setSelected(false);
        if(tbc19.value() % 2 == 1) jToggleButton8.setSelected(true);
    }//GEN-LAST:event_jToggleButton8ActionPerformed

    private void jToggleButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton14ActionPerformed
        tbc20.up();
        
        if(tbc20.value()==2) new LogOutWindow(this, tbc20, jToggleButton14, fir6).setVisible(true);
        if(tbc20.value()>=2) tbc20.down();
            
        if(tbc20.value() % 2 == 0) jToggleButton14.setSelected(false);
        if(tbc20.value() % 2 == 1) jToggleButton14.setSelected(true);
    }//GEN-LAST:event_jToggleButton14ActionPerformed

    private void jToggleButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton19ActionPerformed
        tbc21.up();
        
        if(tbc21.value()==2) new LogOutWindow(this, tbc21, jToggleButton19, fir11).setVisible(true);
        if(tbc21.value()>=2) tbc21.down();
            
        if(tbc21.value() % 2 == 0) jToggleButton19.setSelected(false);
        if(tbc21.value() % 2 == 1) jToggleButton19.setSelected(true);
    }//GEN-LAST:event_jToggleButton19ActionPerformed

    private void jToggleButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton24ActionPerformed
        tbc22.up();
        
        if(tbc22.value()==2) new LogOutWindow(this, tbc22, jToggleButton24, fir17).setVisible(true);
        if(tbc22.value()>=2) tbc22.down();
            
        if(tbc22.value() % 2 == 0) jToggleButton24.setSelected(false);
        if(tbc22.value() % 2 == 1) jToggleButton24.setSelected(true);
    }//GEN-LAST:event_jToggleButton24ActionPerformed

    private void jToggleButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton29ActionPerformed
        tbc23.up();
        
        if(tbc23.value()==2) new LogOutWindow(this, tbc23, jToggleButton29, fir22).setVisible(true);
        if(tbc23.value()>=2) tbc23.down();
            
        if(tbc23.value() % 2 == 0) jToggleButton29.setSelected(false);
        if(tbc23.value() % 2 == 1) jToggleButton29.setSelected(true);
    }//GEN-LAST:event_jToggleButton29ActionPerformed

    private void jToggleButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton34ActionPerformed
        tbc24.up();
        
        if(tbc24.value()==2) new LogOutWindow(this, tbc24, jToggleButton34, fir28).setVisible(true);
        if(tbc24.value()>=2) tbc24.down();
            
        if(tbc24.value() % 2 == 0) jToggleButton34.setSelected(false);
        if(tbc24.value() % 2 == 1) jToggleButton34.setSelected(true);
    }//GEN-LAST:event_jToggleButton34ActionPerformed

    private void jToggleButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton11ActionPerformed
        tbc25.up();
        
        if(tbc25.value()==2) new LogOutWindow(this, tbc25, jToggleButton11, fir3).setVisible(true);
        if(tbc25.value()>=2) tbc25.down();
            
        if(tbc25.value() % 2 == 0) jToggleButton11.setSelected(false);
        if(tbc25.value() % 2 == 1) jToggleButton11.setSelected(true);
    }//GEN-LAST:event_jToggleButton11ActionPerformed

    private void jToggleButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton15ActionPerformed
        tbc26.up();
        
        if(tbc26.value()==2) new LogOutWindow(this, tbc26, jToggleButton15, fir7).setVisible(true);
        if(tbc26.value()>=2) tbc26.down();
            
        if(tbc26.value() % 2 == 0) jToggleButton15.setSelected(false);
        if(tbc26.value() % 2 == 1) jToggleButton15.setSelected(true);
    }//GEN-LAST:event_jToggleButton15ActionPerformed

    private void jToggleButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton20ActionPerformed
        tbc27.up();
        
        if(tbc27.value()==2) new LogOutWindow(this, tbc27, jToggleButton20, fir13).setVisible(true);
        if(tbc27.value()>=2) tbc27.down();
            
        if(tbc27.value() % 2 == 0) jToggleButton20.setSelected(false);
        if(tbc27.value() % 2 == 1) jToggleButton20.setSelected(true);
    }//GEN-LAST:event_jToggleButton20ActionPerformed

    private void jToggleButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton25ActionPerformed
        tbc28.up();
        
        if(tbc28.value()==2) new LogOutWindow(this, tbc28, jToggleButton25, fir18).setVisible(true);
        if(tbc28.value()>=2) tbc28.down();
            
        if(tbc28.value() % 2 == 0) jToggleButton25.setSelected(false);
        if(tbc28.value() % 2 == 1) jToggleButton25.setSelected(true);
    }//GEN-LAST:event_jToggleButton25ActionPerformed

    private void jToggleButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton30ActionPerformed
        tbc29.up();
        
        if(tbc29.value()==2) new LogOutWindow(this, tbc29, jToggleButton30, fir24).setVisible(true);
        if(tbc29.value()>=2) tbc29.down();
            
        if(tbc29.value() % 2 == 0) jToggleButton30.setSelected(false);
        if(tbc29.value() % 2 == 1) jToggleButton30.setSelected(true);
    }//GEN-LAST:event_jToggleButton30ActionPerformed

    private void jToggleButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton35ActionPerformed
        tbc30.up();
        
        if(tbc30.value()==2) new LogOutWindow(this, tbc30, jToggleButton35, fir29).setVisible(true);
        if(tbc30.value()>=2) tbc30.down();
            
        if(tbc30.value() % 2 == 0) jToggleButton35.setSelected(false);
        if(tbc30.value() % 2 == 1) jToggleButton35.setSelected(true);
    }//GEN-LAST:event_jToggleButton35ActionPerformed

    private void jToggleButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton13ActionPerformed
        tbc31.up();
        
        if(tbc31.value()==2) new LogOutWindow(this, tbc31, jToggleButton13, fir5).setVisible(true);
        if(tbc31.value()>=2) tbc31.down();
            
        if(tbc31.value() % 2 == 0) jToggleButton13.setSelected(false);
        if(tbc31.value() % 2 == 1) jToggleButton13.setSelected(true);
    }//GEN-LAST:event_jToggleButton13ActionPerformed

    private void jToggleButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton16ActionPerformed
        tbc32.up();
        
        if(tbc32.value()==2) new LogOutWindow(this, tbc32, jToggleButton16, fir8).setVisible(true);
        if(tbc32.value()>=2) tbc32.down();
            
        if(tbc32.value() % 2 == 0) jToggleButton16.setSelected(false);
        if(tbc32.value() % 2 == 1) jToggleButton16.setSelected(true);
    }//GEN-LAST:event_jToggleButton16ActionPerformed

    private void jToggleButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton21ActionPerformed
        tbc33.up();
        
        if(tbc33.value()==2) new LogOutWindow(this, tbc33, jToggleButton21, fir14).setVisible(true);
        if(tbc33.value()>=2) tbc33.down();
            
        if(tbc33.value() % 2 == 0) jToggleButton21.setSelected(false);
        if(tbc33.value() % 2 == 1) jToggleButton21.setSelected(true);
    }//GEN-LAST:event_jToggleButton21ActionPerformed

    private void jToggleButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton26ActionPerformed
        tbc34.up();
        
        if(tbc34.value()==2) new LogOutWindow(this, tbc34, jToggleButton26, fir19).setVisible(true);
        if(tbc34.value()>=2) tbc34.down();
            
        if(tbc34.value() % 2 == 0) jToggleButton26.setSelected(false);
        if(tbc34.value() % 2 == 1) jToggleButton26.setSelected(true);
    }//GEN-LAST:event_jToggleButton26ActionPerformed

    private void jToggleButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton31ActionPerformed
        tbc35.up();
        
        if(tbc35.value()==2) new LogOutWindow(this, tbc35, jToggleButton31, fir25).setVisible(true);
        if(tbc35.value()>=2) tbc35.down();
            
        if(tbc35.value() % 2 == 0) jToggleButton31.setSelected(false);
        if(tbc35.value() % 2 == 1) jToggleButton31.setSelected(true);
    }//GEN-LAST:event_jToggleButton31ActionPerformed

    private void jToggleButton36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton36ActionPerformed
        tbc36.up();
        
        if(tbc36.value()==2) new LogOutWindow(this, tbc36, jToggleButton36, fir36).setVisible(true);
        if(tbc36.value()>=2) tbc36.down();
            
        if(tbc36.value() % 2 == 0) jToggleButton36.setSelected(false);
        if(tbc36.value() % 2 == 1) jToggleButton36.setSelected(true);
    }//GEN-LAST:event_jToggleButton36ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton10;
    private javax.swing.JToggleButton jToggleButton11;
    private javax.swing.JToggleButton jToggleButton12;
    private javax.swing.JToggleButton jToggleButton13;
    private javax.swing.JToggleButton jToggleButton14;
    private javax.swing.JToggleButton jToggleButton15;
    private javax.swing.JToggleButton jToggleButton16;
    private javax.swing.JToggleButton jToggleButton17;
    private javax.swing.JToggleButton jToggleButton18;
    private javax.swing.JToggleButton jToggleButton19;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton20;
    private javax.swing.JToggleButton jToggleButton21;
    private javax.swing.JToggleButton jToggleButton22;
    private javax.swing.JToggleButton jToggleButton23;
    private javax.swing.JToggleButton jToggleButton24;
    private javax.swing.JToggleButton jToggleButton25;
    private javax.swing.JToggleButton jToggleButton26;
    private javax.swing.JToggleButton jToggleButton27;
    private javax.swing.JToggleButton jToggleButton28;
    private javax.swing.JToggleButton jToggleButton29;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton30;
    private javax.swing.JToggleButton jToggleButton31;
    private javax.swing.JToggleButton jToggleButton32;
    private javax.swing.JToggleButton jToggleButton33;
    private javax.swing.JToggleButton jToggleButton34;
    private javax.swing.JToggleButton jToggleButton35;
    private javax.swing.JToggleButton jToggleButton36;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton8;
    private javax.swing.JToggleButton jToggleButton9;
    // End of variables declaration//GEN-END:variables

    public void tbcReset(ButtonClickCounter btncc, JToggleButton tbtn) {
        btncc.reset();
        if(btncc.value() % 2 == 0) tbtn.setSelected(false);
        if(btncc.value() % 2 == 1) tbtn.setSelected(true);
    }
    
    public void tbcCancel(ButtonClickCounter btncc, JToggleButton tbtn){
        btncc.resetCancel();
        if(btncc.value() % 2 == 0) tbtn.setSelected(false);
        if(btncc.value() % 2 == 1) tbtn.setSelected(true);
    }
}
