/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import BE.ButtonClickCounter;
import javax.swing.JToggleButton;

/**
 *
 * @author Zainz
 */
public class MainFrame extends javax.swing.JFrame {
    
      
    ButtonClickCounter  tbc1,tbc2,tbc3,tbc4,tbc5,tbc6,tbc7,tbc8,tbc9,tbc10,tbc11,
                        tbc12,tbc13,tbc14,tbc15,tbc16,tbc17,tbc18,tbc19,tbc20,
                        tbc21,tbc22,tbc23,tbc24,tbc25,tbc26,tbc27,tbc28,tbc29,
                        tbc30,tbc31,tbc32,tbc33,tbc34,tbc35,tbc36;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        tbc1 = new ButtonClickCounter(0);
        tbc2 = new ButtonClickCounter(0);
        tbc3 = new ButtonClickCounter(0);
        tbc4 = new ButtonClickCounter(0);
        tbc5 = new ButtonClickCounter(0);
        tbc6 = new ButtonClickCounter(0);
        tbc7 = new ButtonClickCounter(0);
        tbc8 = new ButtonClickCounter(0);
        tbc9 = new ButtonClickCounter(0);
        tbc10 = new ButtonClickCounter(0);
        tbc11 = new ButtonClickCounter(0);
        tbc12 = new ButtonClickCounter(0);
        tbc13 = new ButtonClickCounter(0);
        tbc14 = new ButtonClickCounter(0);
        tbc15 = new ButtonClickCounter(0);
        tbc16 = new ButtonClickCounter(0);
        tbc17 = new ButtonClickCounter(0);
        tbc18 = new ButtonClickCounter(0);
        tbc19 = new ButtonClickCounter(0);
        tbc20 = new ButtonClickCounter(0);
        tbc21 = new ButtonClickCounter(0);
        tbc22 = new ButtonClickCounter(0);
        tbc23 = new ButtonClickCounter(0);
        tbc24 = new ButtonClickCounter(0);
        tbc25 = new ButtonClickCounter(0);
        tbc26 = new ButtonClickCounter(0);
        tbc27 = new ButtonClickCounter(0);
        tbc28 = new ButtonClickCounter(0);
        tbc29 = new ButtonClickCounter(0);
        tbc30 = new ButtonClickCounter(0);
        tbc31 = new ButtonClickCounter(0);
        tbc32 = new ButtonClickCounter(0);
        tbc33 = new ButtonClickCounter(0);
        tbc34 = new ButtonClickCounter(0);
        tbc35 = new ButtonClickCounter(0);
        tbc36 = new ButtonClickCounter(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new ColoredToggleButton("name", false);
        jToggleButton2 = new ColoredToggleButton("name", false);
        jToggleButton3 = new ColoredToggleButton("name", false);
        jToggleButton4 = new ColoredToggleButton("name", false);
        jToggleButton5 = new ColoredToggleButton("name", false);
        jToggleButton6 = new ColoredToggleButton("name", false);
        jToggleButton7 = new ColoredToggleButton("name", false);
        jToggleButton8 = new ColoredToggleButton("name", false);
        jToggleButton9 = new ColoredToggleButton("name", false);
        jToggleButton10 = new ColoredToggleButton("name", false);
        jToggleButton11 = new ColoredToggleButton("name", false);
        jToggleButton12 = new ColoredToggleButton("name", false);
        jToggleButton13 = new ColoredToggleButton("name", false);
        jToggleButton14 = new ColoredToggleButton("name", false);
        jToggleButton15 = new ColoredToggleButton("name", false);
        jToggleButton16 = new ColoredToggleButton("name", false);
        jToggleButton17 = new ColoredToggleButton("name", false);
        jToggleButton18 = new ColoredToggleButton("name", false);
        jToggleButton19 = new ColoredToggleButton("name", false);
        jToggleButton20 = new ColoredToggleButton("name", false);
        jToggleButton21 = new ColoredToggleButton("name", false);
        jToggleButton22 = new ColoredToggleButton("name", false);
        jToggleButton23 = new ColoredToggleButton("name", false);
        jToggleButton24 = new ColoredToggleButton("name", false);
        jToggleButton25 = new ColoredToggleButton("name", false);
        jToggleButton26 = new ColoredToggleButton("name", false);
        jToggleButton27 = new ColoredToggleButton("name", false);
        jToggleButton28 = new ColoredToggleButton("name", false);
        jToggleButton29 = new ColoredToggleButton("name", false);
        jToggleButton30 = new ColoredToggleButton("name", false);
        jToggleButton31 = new ColoredToggleButton("name", false);
        jToggleButton32 = new ColoredToggleButton("name", false);
        jToggleButton33 = new ColoredToggleButton("name", false);
        jToggleButton34 = new ColoredToggleButton("name", false);
        jToggleButton35 = new ColoredToggleButton("name", false);
        jToggleButton36 = new ColoredToggleButton("name", false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 780));
        setResizable(false);

        jToggleButton1.setText("jToggleButton1");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jToggleButton2.setText("jToggleButton2");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jToggleButton3.setText("jToggleButton3");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });

        jToggleButton4.setText("jToggleButton4");
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });

        jToggleButton5.setText("jToggleButton5");
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });

        jToggleButton6.setText("jToggleButton6");
        jToggleButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton6ActionPerformed(evt);
            }
        });

        jToggleButton7.setText("jToggleButton7");
        jToggleButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton7ActionPerformed(evt);
            }
        });

        jToggleButton8.setText("jToggleButton8");
        jToggleButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton8ActionPerformed(evt);
            }
        });

        jToggleButton9.setText("jToggleButton9");
        jToggleButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton9ActionPerformed(evt);
            }
        });

        jToggleButton10.setText("jToggleButton10");
        jToggleButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton10ActionPerformed(evt);
            }
        });

        jToggleButton11.setText("jToggleButton11");
        jToggleButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton11ActionPerformed(evt);
            }
        });

        jToggleButton12.setText("jToggleButton12");
        jToggleButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton12ActionPerformed(evt);
            }
        });

        jToggleButton13.setText("jToggleButton13");
        jToggleButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton13ActionPerformed(evt);
            }
        });

        jToggleButton14.setText("jToggleButton14");
        jToggleButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton14ActionPerformed(evt);
            }
        });

        jToggleButton15.setText("jToggleButton15");
        jToggleButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton15ActionPerformed(evt);
            }
        });

        jToggleButton16.setText("jToggleButton16");
        jToggleButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton16ActionPerformed(evt);
            }
        });

        jToggleButton17.setText("jToggleButton17");
        jToggleButton17.setToolTipText("");
        jToggleButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton17ActionPerformed(evt);
            }
        });

        jToggleButton18.setText("jToggleButton18");
        jToggleButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton18ActionPerformed(evt);
            }
        });

        jToggleButton19.setText("jToggleButton19");
        jToggleButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton19ActionPerformed(evt);
            }
        });

        jToggleButton20.setText("jToggleButton20");
        jToggleButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton20ActionPerformed(evt);
            }
        });

        jToggleButton21.setText("jToggleButton21");
        jToggleButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton21ActionPerformed(evt);
            }
        });

        jToggleButton22.setText("jToggleButton22");
        jToggleButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton22ActionPerformed(evt);
            }
        });

        jToggleButton23.setText("jToggleButton23");
        jToggleButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton23ActionPerformed(evt);
            }
        });

        jToggleButton24.setText("jToggleButton24");
        jToggleButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton24ActionPerformed(evt);
            }
        });

        jToggleButton25.setText("jToggleButton25");
        jToggleButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton25ActionPerformed(evt);
            }
        });

        jToggleButton26.setText("jToggleButton26");
        jToggleButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton26ActionPerformed(evt);
            }
        });

        jToggleButton27.setText("jToggleButton27");
        jToggleButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton27ActionPerformed(evt);
            }
        });

        jToggleButton28.setText("jToggleButton28");
        jToggleButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton28ActionPerformed(evt);
            }
        });

        jToggleButton29.setText("jToggleButton29");
        jToggleButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton29ActionPerformed(evt);
            }
        });

        jToggleButton30.setText("jToggleButton30");
        jToggleButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton30ActionPerformed(evt);
            }
        });

        jToggleButton31.setText("jToggleButton31");
        jToggleButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton31ActionPerformed(evt);
            }
        });

        jToggleButton32.setText("jToggleButton32");
        jToggleButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton32ActionPerformed(evt);
            }
        });

        jToggleButton33.setText("jToggleButton33");
        jToggleButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton33ActionPerformed(evt);
            }
        });

        jToggleButton34.setText("jToggleButton34");
        jToggleButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton34ActionPerformed(evt);
            }
        });

        jToggleButton35.setText("jToggleButton35");
        jToggleButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton35ActionPerformed(evt);
            }
        });

        jToggleButton36.setText("jToggleButton36");
        jToggleButton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton36ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToggleButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton32, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton33, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton34, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton35, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton36, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToggleButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton27, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton28, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton29, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton30, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton31, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton25, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton26, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToggleButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jToggleButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jToggleButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jToggleButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jToggleButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jToggleButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jToggleButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jToggleButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jToggleButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton25, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton26, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton27, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton28, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton29, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton30, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton31, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton32, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton33, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton34, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton35, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton36, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        tbc1.up();
        
        if(tbc1.value()==2) new LogOutWindow(this, tbc1, jToggleButton1).setVisible(true);
        if(tbc1.value()>=2) tbc1.down();
            
        if(tbc1.value() % 2 == 0) jToggleButton1.setSelected(false);
        if(tbc1.value() % 2 == 1) jToggleButton1.setSelected(true);
        
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        tbc2.up();
        
        if(tbc2.value()==2) new LogOutWindow(this, tbc2, jToggleButton2).setVisible(true);
        if(tbc2.value()>=2) tbc2.down();
            
        if(tbc2.value() % 2 == 0) jToggleButton2.setSelected(false);
        if(tbc2.value() % 2 == 1) jToggleButton2.setSelected(true);
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton6ActionPerformed
        tbc3.up();
        
        if(tbc3.value()==2) new LogOutWindow(this, tbc3, jToggleButton6).setVisible(true);
        if(tbc3.value()>=2) tbc3.down();
            
        if(tbc3.value() % 2 == 0) jToggleButton6.setSelected(false);
        if(tbc3.value() % 2 == 1) jToggleButton6.setSelected(true);
    }//GEN-LAST:event_jToggleButton6ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        tbc1.up();
        
        if(tbc1.value()==2) new LogOutWindow(this, tbc1, jToggleButton1).setVisible(true);
        if(tbc1.value()>=2) tbc1.down();
            
        if(tbc1.value() % 2 == 0) jToggleButton1.setSelected(false);
        if(tbc1.value() % 2 == 1) jToggleButton1.setSelected(true);
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        tbc1.up();
        
        if(tbc1.value()==2) new LogOutWindow(this, tbc1, jToggleButton1).setVisible(true);
        if(tbc1.value()>=2) tbc1.down();
            
        if(tbc1.value() % 2 == 0) jToggleButton1.setSelected(false);
        if(tbc1.value() % 2 == 1) jToggleButton1.setSelected(true);
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
        tbc1.up();
        
        if(tbc1.value()==2) new LogOutWindow(this, tbc1, jToggleButton1).setVisible(true);
        if(tbc1.value()>=2) tbc1.down();
            
        if(tbc1.value() % 2 == 0) jToggleButton1.setSelected(false);
        if(tbc1.value() % 2 == 1) jToggleButton1.setSelected(true);
    }//GEN-LAST:event_jToggleButton5ActionPerformed

    private void jToggleButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton9ActionPerformed
        tbc1.up();
        
        if(tbc1.value()==2) new LogOutWindow(this, tbc1, jToggleButton1).setVisible(true);
        if(tbc1.value()>=2) tbc1.down();
            
        if(tbc1.value() % 2 == 0) jToggleButton1.setSelected(false);
        if(tbc1.value() % 2 == 1) jToggleButton1.setSelected(true);
    }//GEN-LAST:event_jToggleButton9ActionPerformed

    private void jToggleButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton10ActionPerformed
        tbc1.up();
        
        if(tbc1.value()==2) new LogOutWindow(this, tbc1, jToggleButton1).setVisible(true);
        if(tbc1.value()>=2) tbc1.down();
            
        if(tbc1.value() % 2 == 0) jToggleButton1.setSelected(false);
        if(tbc1.value() % 2 == 1) jToggleButton1.setSelected(true);
    }//GEN-LAST:event_jToggleButton10ActionPerformed

    private void jToggleButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton17ActionPerformed
        tbc1.up();
        
        if(tbc1.value()==2) new LogOutWindow(this, tbc1, jToggleButton1).setVisible(true);
        if(tbc1.value()>=2) tbc1.down();
            
        if(tbc1.value() % 2 == 0) jToggleButton1.setSelected(false);
        if(tbc1.value() % 2 == 1) jToggleButton1.setSelected(true);
    }//GEN-LAST:event_jToggleButton17ActionPerformed

    private void jToggleButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton22ActionPerformed
        tbc1.up();
        
        if(tbc1.value()==2) new LogOutWindow(this, tbc1, jToggleButton1).setVisible(true);
        if(tbc1.value()>=2) tbc1.down();
            
        if(tbc1.value() % 2 == 0) jToggleButton1.setSelected(false);
        if(tbc1.value() % 2 == 1) jToggleButton1.setSelected(true);
    }//GEN-LAST:event_jToggleButton22ActionPerformed

    private void jToggleButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton27ActionPerformed
        tbc1.up();
        
        if(tbc1.value()==2) new LogOutWindow(this, tbc1, jToggleButton1).setVisible(true);
        if(tbc1.value()>=2) tbc1.down();
            
        if(tbc1.value() % 2 == 0) jToggleButton1.setSelected(false);
        if(tbc1.value() % 2 == 1) jToggleButton1.setSelected(true);
    }//GEN-LAST:event_jToggleButton27ActionPerformed

    private void jToggleButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton32ActionPerformed
        tbc1.up();
        
        if(tbc1.value()==2) new LogOutWindow(this, tbc1, jToggleButton1).setVisible(true);
        if(tbc1.value()>=2) tbc1.down();
            
        if(tbc1.value() % 2 == 0) jToggleButton1.setSelected(false);
        if(tbc1.value() % 2 == 1) jToggleButton1.setSelected(true);
    }//GEN-LAST:event_jToggleButton32ActionPerformed

    private void jToggleButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton7ActionPerformed
        tbc1.up();
        
        if(tbc1.value()==2) new LogOutWindow(this, tbc1, jToggleButton1).setVisible(true);
        if(tbc1.value()>=2) tbc1.down();
            
        if(tbc1.value() % 2 == 0) jToggleButton1.setSelected(false);
        if(tbc1.value() % 2 == 1) jToggleButton1.setSelected(true);
    }//GEN-LAST:event_jToggleButton7ActionPerformed

    private void jToggleButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton12ActionPerformed
        tbc1.up();
        
        if(tbc1.value()==2) new LogOutWindow(this, tbc1, jToggleButton1).setVisible(true);
        if(tbc1.value()>=2) tbc1.down();
            
        if(tbc1.value() % 2 == 0) jToggleButton1.setSelected(false);
        if(tbc1.value() % 2 == 1) jToggleButton1.setSelected(true);
    }//GEN-LAST:event_jToggleButton12ActionPerformed

    private void jToggleButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton18ActionPerformed
        tbc1.up();
        
        if(tbc1.value()==2) new LogOutWindow(this, tbc1, jToggleButton1).setVisible(true);
        if(tbc1.value()>=2) tbc1.down();
            
        if(tbc1.value() % 2 == 0) jToggleButton1.setSelected(false);
        if(tbc1.value() % 2 == 1) jToggleButton1.setSelected(true);
    }//GEN-LAST:event_jToggleButton18ActionPerformed

    private void jToggleButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton23ActionPerformed
        tbc1.up();
        
        if(tbc1.value()==2) new LogOutWindow(this, tbc1, jToggleButton1).setVisible(true);
        if(tbc1.value()>=2) tbc1.down();
            
        if(tbc1.value() % 2 == 0) jToggleButton1.setSelected(false);
        if(tbc1.value() % 2 == 1) jToggleButton1.setSelected(true);
    }//GEN-LAST:event_jToggleButton23ActionPerformed

    private void jToggleButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton28ActionPerformed
        tbc1.up();
        
        if(tbc1.value()==2) new LogOutWindow(this, tbc1, jToggleButton1).setVisible(true);
        if(tbc1.value()>=2) tbc1.down();
            
        if(tbc1.value() % 2 == 0) jToggleButton1.setSelected(false);
        if(tbc1.value() % 2 == 1) jToggleButton1.setSelected(true);
    }//GEN-LAST:event_jToggleButton28ActionPerformed

    private void jToggleButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton33ActionPerformed
        tbc1.up();
        
        if(tbc1.value()==2) new LogOutWindow(this, tbc1, jToggleButton1).setVisible(true);
        if(tbc1.value()>=2) tbc1.down();
            
        if(tbc1.value() % 2 == 0) jToggleButton1.setSelected(false);
        if(tbc1.value() % 2 == 1) jToggleButton1.setSelected(true);
    }//GEN-LAST:event_jToggleButton33ActionPerformed

    private void jToggleButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton8ActionPerformed
        tbc1.up();
        
        if(tbc1.value()==2) new LogOutWindow(this, tbc1, jToggleButton1).setVisible(true);
        if(tbc1.value()>=2) tbc1.down();
            
        if(tbc1.value() % 2 == 0) jToggleButton1.setSelected(false);
        if(tbc1.value() % 2 == 1) jToggleButton1.setSelected(true);
    }//GEN-LAST:event_jToggleButton8ActionPerformed

    private void jToggleButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton14ActionPerformed
        tbc1.up();
        
        if(tbc1.value()==2) new LogOutWindow(this, tbc1, jToggleButton1).setVisible(true);
        if(tbc1.value()>=2) tbc1.down();
            
        if(tbc1.value() % 2 == 0) jToggleButton1.setSelected(false);
        if(tbc1.value() % 2 == 1) jToggleButton1.setSelected(true);
    }//GEN-LAST:event_jToggleButton14ActionPerformed

    private void jToggleButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton19ActionPerformed
        tbc1.up();
        
        if(tbc1.value()==2) new LogOutWindow(this, tbc1, jToggleButton1).setVisible(true);
        if(tbc1.value()>=2) tbc1.down();
            
        if(tbc1.value() % 2 == 0) jToggleButton1.setSelected(false);
        if(tbc1.value() % 2 == 1) jToggleButton1.setSelected(true);
    }//GEN-LAST:event_jToggleButton19ActionPerformed

    private void jToggleButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton24ActionPerformed
        tbc1.up();
        
        if(tbc1.value()==2) new LogOutWindow(this, tbc1, jToggleButton1).setVisible(true);
        if(tbc1.value()>=2) tbc1.down();
            
        if(tbc1.value() % 2 == 0) jToggleButton1.setSelected(false);
        if(tbc1.value() % 2 == 1) jToggleButton1.setSelected(true);
    }//GEN-LAST:event_jToggleButton24ActionPerformed

    private void jToggleButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton29ActionPerformed
        tbc1.up();
        
        if(tbc1.value()==2) new LogOutWindow(this, tbc1, jToggleButton1).setVisible(true);
        if(tbc1.value()>=2) tbc1.down();
            
        if(tbc1.value() % 2 == 0) jToggleButton1.setSelected(false);
        if(tbc1.value() % 2 == 1) jToggleButton1.setSelected(true);
    }//GEN-LAST:event_jToggleButton29ActionPerformed

    private void jToggleButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton34ActionPerformed
        tbc1.up();
        
        if(tbc1.value()==2) new LogOutWindow(this, tbc1, jToggleButton1).setVisible(true);
        if(tbc1.value()>=2) tbc1.down();
            
        if(tbc1.value() % 2 == 0) jToggleButton1.setSelected(false);
        if(tbc1.value() % 2 == 1) jToggleButton1.setSelected(true);
    }//GEN-LAST:event_jToggleButton34ActionPerformed

    private void jToggleButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton11ActionPerformed
        tbc1.up();
        
        if(tbc1.value()==2) new LogOutWindow(this, tbc1, jToggleButton1).setVisible(true);
        if(tbc1.value()>=2) tbc1.down();
            
        if(tbc1.value() % 2 == 0) jToggleButton1.setSelected(false);
        if(tbc1.value() % 2 == 1) jToggleButton1.setSelected(true);
    }//GEN-LAST:event_jToggleButton11ActionPerformed

    private void jToggleButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton15ActionPerformed
        tbc1.up();
        
        if(tbc1.value()==2) new LogOutWindow(this, tbc1, jToggleButton1).setVisible(true);
        if(tbc1.value()>=2) tbc1.down();
            
        if(tbc1.value() % 2 == 0) jToggleButton1.setSelected(false);
        if(tbc1.value() % 2 == 1) jToggleButton1.setSelected(true);
    }//GEN-LAST:event_jToggleButton15ActionPerformed

    private void jToggleButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton20ActionPerformed
        tbc1.up();
        
        if(tbc1.value()==2) new LogOutWindow(this, tbc1, jToggleButton1).setVisible(true);
        if(tbc1.value()>=2) tbc1.down();
            
        if(tbc1.value() % 2 == 0) jToggleButton1.setSelected(false);
        if(tbc1.value() % 2 == 1) jToggleButton1.setSelected(true);
    }//GEN-LAST:event_jToggleButton20ActionPerformed

    private void jToggleButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton25ActionPerformed
        tbc1.up();
        
        if(tbc1.value()==2) new LogOutWindow(this, tbc1, jToggleButton1).setVisible(true);
        if(tbc1.value()>=2) tbc1.down();
            
        if(tbc1.value() % 2 == 0) jToggleButton1.setSelected(false);
        if(tbc1.value() % 2 == 1) jToggleButton1.setSelected(true);
    }//GEN-LAST:event_jToggleButton25ActionPerformed

    private void jToggleButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton30ActionPerformed
        tbc1.up();
        
        if(tbc1.value()==2) new LogOutWindow(this, tbc1, jToggleButton1).setVisible(true);
        if(tbc1.value()>=2) tbc1.down();
            
        if(tbc1.value() % 2 == 0) jToggleButton1.setSelected(false);
        if(tbc1.value() % 2 == 1) jToggleButton1.setSelected(true);
    }//GEN-LAST:event_jToggleButton30ActionPerformed

    private void jToggleButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton35ActionPerformed
        tbc1.up();
        
        if(tbc1.value()==2) new LogOutWindow(this, tbc1, jToggleButton1).setVisible(true);
        if(tbc1.value()>=2) tbc1.down();
            
        if(tbc1.value() % 2 == 0) jToggleButton1.setSelected(false);
        if(tbc1.value() % 2 == 1) jToggleButton1.setSelected(true);
    }//GEN-LAST:event_jToggleButton35ActionPerformed

    private void jToggleButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton13ActionPerformed
        tbc1.up();
        
        if(tbc1.value()==2) new LogOutWindow(this, tbc1, jToggleButton1).setVisible(true);
        if(tbc1.value()>=2) tbc1.down();
            
        if(tbc1.value() % 2 == 0) jToggleButton1.setSelected(false);
        if(tbc1.value() % 2 == 1) jToggleButton1.setSelected(true);
    }//GEN-LAST:event_jToggleButton13ActionPerformed

    private void jToggleButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton16ActionPerformed
        tbc1.up();
        
        if(tbc1.value()==2) new LogOutWindow(this, tbc1, jToggleButton1).setVisible(true);
        if(tbc1.value()>=2) tbc1.down();
            
        if(tbc1.value() % 2 == 0) jToggleButton1.setSelected(false);
        if(tbc1.value() % 2 == 1) jToggleButton1.setSelected(true);
    }//GEN-LAST:event_jToggleButton16ActionPerformed

    private void jToggleButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton21ActionPerformed
        tbc1.up();
        
        if(tbc1.value()==2) new LogOutWindow(this, tbc1, jToggleButton1).setVisible(true);
        if(tbc1.value()>=2) tbc1.down();
            
        if(tbc1.value() % 2 == 0) jToggleButton1.setSelected(false);
        if(tbc1.value() % 2 == 1) jToggleButton1.setSelected(true);
    }//GEN-LAST:event_jToggleButton21ActionPerformed

    private void jToggleButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton26ActionPerformed
        tbc1.up();
        
        if(tbc1.value()==2) new LogOutWindow(this, tbc1, jToggleButton1).setVisible(true);
        if(tbc1.value()>=2) tbc1.down();
            
        if(tbc1.value() % 2 == 0) jToggleButton1.setSelected(false);
        if(tbc1.value() % 2 == 1) jToggleButton1.setSelected(true);
    }//GEN-LAST:event_jToggleButton26ActionPerformed

    private void jToggleButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton31ActionPerformed
        tbc1.up();
        
        if(tbc1.value()==2) new LogOutWindow(this, tbc1, jToggleButton1).setVisible(true);
        if(tbc1.value()>=2) tbc1.down();
            
        if(tbc1.value() % 2 == 0) jToggleButton1.setSelected(false);
        if(tbc1.value() % 2 == 1) jToggleButton1.setSelected(true);
    }//GEN-LAST:event_jToggleButton31ActionPerformed

    private void jToggleButton36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton36ActionPerformed
        tbc1.up();
        
        if(tbc1.value()==2) new LogOutWindow(this, tbc1, jToggleButton1).setVisible(true);
        if(tbc1.value()>=2) tbc1.down();
            
        if(tbc1.value() % 2 == 0) jToggleButton1.setSelected(false);
        if(tbc1.value() % 2 == 1) jToggleButton1.setSelected(true);
    }//GEN-LAST:event_jToggleButton36ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton10;
    private javax.swing.JToggleButton jToggleButton11;
    private javax.swing.JToggleButton jToggleButton12;
    private javax.swing.JToggleButton jToggleButton13;
    private javax.swing.JToggleButton jToggleButton14;
    private javax.swing.JToggleButton jToggleButton15;
    private javax.swing.JToggleButton jToggleButton16;
    private javax.swing.JToggleButton jToggleButton17;
    private javax.swing.JToggleButton jToggleButton18;
    private javax.swing.JToggleButton jToggleButton19;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton20;
    private javax.swing.JToggleButton jToggleButton21;
    private javax.swing.JToggleButton jToggleButton22;
    private javax.swing.JToggleButton jToggleButton23;
    private javax.swing.JToggleButton jToggleButton24;
    private javax.swing.JToggleButton jToggleButton25;
    private javax.swing.JToggleButton jToggleButton26;
    private javax.swing.JToggleButton jToggleButton27;
    private javax.swing.JToggleButton jToggleButton28;
    private javax.swing.JToggleButton jToggleButton29;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton30;
    private javax.swing.JToggleButton jToggleButton31;
    private javax.swing.JToggleButton jToggleButton32;
    private javax.swing.JToggleButton jToggleButton33;
    private javax.swing.JToggleButton jToggleButton34;
    private javax.swing.JToggleButton jToggleButton35;
    private javax.swing.JToggleButton jToggleButton36;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton8;
    private javax.swing.JToggleButton jToggleButton9;
    // End of variables declaration//GEN-END:variables

    public void tbcReset(ButtonClickCounter btncc, JToggleButton tbtn) {
        btncc.reset();
        if(btncc.value() % 2 == 0) tbtn.setSelected(false);
        if(btncc.value() % 2 == 1) tbtn.setSelected(true);
    }
}
